make:
	g++ src/main.cpp src/accountuser.cpp src/loginwindow.cpp src/databaseconnect.cpp src/dashboard.cpp -o app `wx-config --cxxflags --libs` -lsodium \
	-I/usr/local/include -L/usr/local/lib/mariadb -lmariadbcpp
